runtime: nodejs
env: flex
env_variables:  
  MONGO_CONECTION: mongodb://ejecentral:ejecentral@clustercdmx-shard-00-00-wysw9.gcp.mongodb.net:27017,clustercdmx-shard-00-01-wysw9.gcp.mongodb.net:27017,clustercdmx-shard-00-02-wysw9.gcp.mongodb.net:27017/test?ssl=true&replicaSet=ClusterCDMX-shard-0&authSource=admin&retryWrites=true
  SECRET_PSW: lasldkalskdalkdngnggnadseeqw13
  POSSIBLE: ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789
  HOST: smtp.ionos.mx
  USERMAIL: sistema@ejecentral.studio
  USERPASS: ZV9UeaLm4r7E4Jd
  MAILPORT: 465